name: CI/CD Pipeline - Frontend

on:
  push:
    branches:
      - main
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'  

      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm

      - name: Install dependencies
        run: npm install

      - name: Run tests (allow failure)
        run: npm test || true

  build-frontend:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Angular project
        run: npm run build --prod  

  deploy-to-vm:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Install openconnect
        run: |
          sudo apt-get update
          sudo apt-get install -y openconnect

      - name: Connect to VPN
        run: |
          echo "${{ secrets.VPN_PASSWORD }}" | sudo openconnect --user=${{ secrets.VPN_USERNAME }} --passwd-on-stdin --authgroup="Etudiants de l' UGA" ${{ secrets.VPN_URL }} &
          sleep 10 # Attendez que le VPN soit pleinement connecté

      - name: Deploy Angular app to VM
        run: |
          sshpass -p "$VM_PASSWORD" ssh -o StrictHostKeyChecking=no $VM_USERNAME@129.88.210.194 << 'EOF'
          # Copier les fichiers de build Angular vers le serveur
          mkdir -p /var/www/html/angular-app
          rm -rf /var/www/html/angular-app/*
          cp -r $GITHUB_WORKSPACE/dist/* /var/www/html/angular-app/

          # Démarrer un serveur HTTP pour servir l'application Angular
          sudo apt-get install -y http-server
          cd /var/www/html/angular-app
          nohup http-server -p 80 &  # Lancer l'application en arrière-plan
          EOF
        env:
          VM_USERNAME: ${{ secrets.VM_USERNAME }}
          VM_PASSWORD: ${{ secrets.VM_PASSWORD }}
